### ISSUE TITLE
Question for bedtools promoter error

### ISSUE THREAD

**Issue by mxiong2** [Genotek/ClassifyCNV#10]
I keep getting this error. I am not sure if its my CNV bedfile.

***** ERROR: illegal number "4.2e+07". Exiting...

***** ERROR: illegal number "4.2e+07". Exiting...

ERROR when running BEDTools on  promoters

**Comment by tgurbich** [comment]
Hello,
It looks like this error is caused by how the start and end positions of the CNVs are written in your input file. Could you please edit it to make sure all numbers are written out in full and not as "4.2e+07" and try again? This should solve the issue.

**Comment by mxiong2** [comment]
Thank you! That worked.
