### ISSUE TITLE
Missing 5th column on line 533 of ClinGen_triplosensitivity_gene.bed

### ISSUE THREAD

**Issue by ffmmulder** [Genotek/ClassifyCNV#2]
Both hg19 and hg38 versions of the 'ClinGen_triplosensitivity_gene.bed' file miss the 5th column on line 533 (ERCC3 gene) causing a crash. (Easily fixable by either removing the line or adding the 5th column )

Exmaple: line from the hg19 version: 
chr2	128014865	128051752	ERCC3

**Comment by tgurbich** [comment]
Dear @ffmmulder,

Thank you for using ClassifyCNV and for spotting this problem. Looks like the older version of this ClinGen file was indeed missing the value in the fifth column for the ERCC3 gene. I've updated all ClinGen files used in the repo and this error should no longer occur. 

As ClinGen updates their databases daily, we recommend that the users always download the newest available files before running ClassifyCNV by executing the `update_clingen.sh` script. I've updated the updater script (`parse_clingen_tsv.py`) as well so please use the latest version.
