### ISSUE TITLE
NameError: name 'default_results_folder' is not defined

### ISSUE THREAD

**Issue by psychrb** [Genotek/ClassifyCNV#4]
I just tried running ClassifyCNV on a test bed file but get an error related to the output directory..This occurs whether I specify a path and file name after --outdir or just leave it blank without adding a flag...Is this a bug, or am I entering something wrong? Thanks.

COMMAND LINE:
python3 ClassifyCNV.py --infile XYZ.bed --GenomeBuild hg19 --outdir OUT_TEST

ERROR:
Traceback (most recent call last):
  File "ClassifyCNV.py", line 25, in <module>
    parser.add_argument('--outdir', default=default_results_folder,
NameError: name 'default_results_folder' is not defined

**Comment by tgurbich** [comment]
Hi @psychrb,

It sounds like something isn't right with your local version of the resources.py script. Could you please try to clone the repo again and see if that resolves the problem?

```
git clone https://github.com/Genotek/ClassifyCNV
cd ClassifyCNV
python3 ClassifyCNV.py -h
```

Please let me know if this works.

**Comment by psychrb** [comment]
Thanks. OK. I was running it in a different directory than the resources.py script. Working now. Thanks
