### ISSUE TITLE
 Question about the population frequency database

### ISSUE THREAD

**Issue by Rojay-hub** [Genotek/ClassifyCNV#7]
Hi, 
    I haved tried  ClassifyCNV recently, and this  is a excellent software.  Here, I wonder how the  population frequencies database (population_freqs.bed file) was obtained.  Does it integrated from DGV and gnomAD? 
Thanks very much. 

Best，
Niki

**Comment by tgurbich** [comment]
Hi! 

Thank you for your interest in ClassifyCNV. You are exactly right - population_freqs.bed is the combination of the DGV gold standard variants and gnomAD structural variant frequencies. Here are the links to the original source files for hg19 in case you are interested: [DGV](http://dgv.tcag.ca/dgv/docs/DGV.GS.March2016.50percent.GainLossSep.Final.hg19.gff3) and [gnomAD](https://storage.googleapis.com/gcp-public-data--gnomad/papers/2019-sv/gnomad_v2.1_sv.sites.bed.gz).

**Comment by Rojay-hub** [comment]
Dear @tgurbich,
        Thank you for your response. Now I understand it more clearly.
Best
